name: build-release
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      maven-version: "3.9.8"
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: 
          name: apache-maven-3.9.8.msi              
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "apache-maven-3.9.8.msi"
          omitBody: true
