name: Build

on:
  workflow_call:
    inputs:
      maven-version:
        required: true
        type: string
jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Install WiX
        run: dotnet tool install --global wix
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build WiX on Windows
        shell: powershell
        run: ./build.ps1 -version ${{ inputs.maven-version }}
      - name: Archive installer
        uses: actions/upload-artifact@v4
        with:
          name: apache-maven-3.9.8.msi
          path: ./apache-maven-3.9.8.msi
