name: Build Release
on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build-installer.yml
    with:
      maven-version: 3.9.8
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: 
          name: apache-maven-3.9.8.msi              
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "apache-maven-3.9.8.msi"
          omitBody: true
          draft: true
