name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Install WiX
        run: dotnet tool install --global wix
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build WiX on Windows
        shell: powershell
        run: ./build.ps1 -version 3.9.8
      - name: Archive installer
        uses: actions/upload-artifact@v4
        with:
          name: apache-maven-3.9.8.msi
          path: ./apache-maven-3.9.8.msi
